import { createContext, useContext, useState, useEffect } from 'react';
import { flushSync } from 'react-dom';

const ModeContext = createContext();

export function ModeProvider({ children }) {
  // 1. State Mode (UMKM / Personal)
  const [mode, setMode] = useState(() => localStorage.getItem('kasflow-mode') || 'umkm');

  // 2. State Theme (Light / Dark)
  const [theme, setTheme] = useState(() => {
    const saved = localStorage.getItem('theme');
    if (saved) return saved;
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  });

  // 3. State Notifications
  const [notifications, setNotifications] = useState(() => {
    const saved = localStorage.getItem('notifications');
    return saved !== null ? JSON.parse(saved) : true;
  });

  // 4. State Bahasa (Global)
  const [language, setLanguage] = useState(() => localStorage.getItem('kasflow-lang') || 'Indonesia');

  // --- KAMUS TRANSLASI LENGKAP ---
const translations = {
  "Indonesia": {
    mobile_summary_prefix: "Ringkasan kas",
    mobile_summary_suffix: "hari ini.",
    // Sidebar & Navigation
    nav_dashboard: "Dashboard",
    nav_transaksi: "Transaksi",
    nav_insight: "Insight",
    nav_profil: "Profil",
    nav_beranda: "Beranda",
    btn_catat: "Catat Transaksi",
    mode_p_short: "Personal",
    mode_u_short: "UMKM",
    // Dashboard Page
    hello: "Halo",
    search_trans: "Cari riwayat transaksi...",
    this_month: "bulan ini",
    total_balance: "Total Saldo Aktif",
    income: "Pemasukan",
    expense: "Pengeluaran",
    cashflow_trend: "Tren Arus Kas",
    category_dist: "Distribusi Kategori",
    quick_action: "Aksi Cepat",
    add_income: "Tambah Pemasukan",
    add_expense: "Tambah Pengeluaran",
    scan_receipt: "Scan Struk / Nota",
    scanning: "Memindai...",
    fin_health: "Kesehatan Finansial",
    very_healthy: "Sangat Sehat",
    spending_controlled: "Pengeluaran terkendali",
    spending_optimized: "Pengeluaran telah dioptimalkan",
    critical: "Kritis",
    warning: "Waspada",
    safe: "Aman",
    danger: "Bahaya",
    risk_level: "Tingkat Risiko",
    recent_trans: "Riwayat Transaksi Terbaru",
    view_all: "Lihat Semua",
    trans_type: "Tipe Transaksi",
    cat_action: "Kategori & Aktivitas",
    date_time: "Tanggal & Waktu",
    status_label: "Status",
    done: "Selesai",
    pending: "Tertunda",
    // Add Transaction Page
    add_title: "Catat Transaksi",
    add_desc: "Masukkan nominal kas baru di sini.",
    amount: "Nominal",
    trans_name: "Nama Transaksi",
    placeholder_name: "Contoh: Beli Token Listrik, Gaji...",
    category: "Kategori",
    select_category: "Pilih Kategori",
    notes: "Catatan",
    placeholder_notes: "Tulis detail transaksi...",
    save: "Simpan Transaksi",
    saving: "Menyimpan...",
    success_save: "Berhasil mencatat",
    error_name: "Nama transaksi belum diisi!",
    error_amount: "Nominal tidak boleh kosong!",
    error_category: "Kategori belum diisi!",
    error_save: "Gagal menyimpan transaksi.",
    // Kategori
    cat_sales: "Penjualan",
    cat_service: "Pendapatan Jasa",
    cat_capital: "Modal",
    cat_raw: "Bahan Baku",
    cat_ops: "Operasional",
    cat_marketing: "Pemasaran",
    cat_salary: "Gaji Pokok",
    cat_bills: "Tagihan",
    cat_rent: "Sewa",
    cat_others: "Lain-lain",
    // Transactions Page (NEW)
    trans_desc: "Pantau riwayat lengkap sirkulasi keuangan KasFlow dalam satu layar lebar.",
    trans_desc_mobile: "Pantau semua pengeluaran dan pemasukanmu.",
    trans_not_found: "Transaksi tidak ditemukan",
    trans_not_found_desc: "Tidak ada riwayat yang cocok dengan kata kunci Anda.",
    export_title: "Ekspor Laporan",
    export_pdf: "Unduh PDF",
    export_csv: "Unduh CSV",
    // Insight Page (FIX image_011a3f.png & image_012186.png)
    analytics: "Analisis Keuangan",
    monthly_report: "Laporan Bulanan",
    spending_graph: "Grafik Pengeluaran",
    insight_subtitle: "Analisis mendalam seputar arus kasmu.",
    smart_insight: "Insight Cerdas",
    insight_spending_prefix: "Pengeluaran terbesarmu bulan ini ada di kategori",
    insight_tip_personal: "Coba kurangi jajan di luar untuk berhemat.",
    insight_tip_umkm: "Pastikan harga jual produkmu sudah menutupi modal ini.",
    based_on: "Berdasarkan pengeluaran",
    master_finansial: "Master Finansial",
    to_level: "ke Level 5",
    gamification_tip: "Hebat! Pengeluaranmu 15% lebih irit bulan ini (+50 XP). Terus pertahankan!",
    more_saving: "Lebih Hemat",
    vs_last_month: "Bulan ini vs Bulan lalu",
    budget_category: "Anggaran Kategori",
    budget_desc: "Pantau batas pengeluaranmu dari budget",
    budget_warning: "Peringatan: Anggaran berlebih!",
    top_5_expense: "Top 5 Pengeluaran",
    biggest_spending: "Pengeluaran terbesar bulan ini",
    insight_footer_title: "Jaga Pengeluaran Anda",
    insight_footer_desc: "Tetap berada dalam anggaran bulan ini untuk mencapai target tabungan Anda.",
    add_budget_title: "Tambah Anggaran Baru",
    add_budget_desc: "Atur batas anggaran belanja untuk kategori tambahan.",
    custom_category: "Kategori Custom Baru...",
    net_profit: "Laba Bersih",
    gross_income: "Pendapatan Kotor",
    total_cost: "Total Biaya",
    profit_margin: "Margin Laba",
    last_month: "Bulan Lalu",
    this_month_chart: "Bulan Ini",
    // Gamification & Badges
    financial_level: "Level Finansial",
    score_label: "Skor",
    progress_to: "Progres ke Level",
    collect_more_prefix: "Kumpulkan",
    collect_more_suffix: "lagi.",
    max_level_reached: "Selamat, kamu mencapai level maksimal!",
    daily_missions: "Misi Harian",
    streak_days: "5 Hari Beruntun!",
    mission_xp_desc: "Selesaikan untuk dapatkan XP tambahan",
    level_up_notif: "Level Up!",
    congrats_reach: "Selamat! Kamu mencapai peringkat",
    achievement_unlocked: "Pencapaian Terbuka!",
    new_badge_collect: "Satu lagi koleksi badge kamu:",
    continue: "Lanjutkan",
    claim: "Klaim!",
    top_user_percent: "Kamu di top 15% pengguna!",
    mission_daily_exp: "Catat pengeluaran hari ini",
    mission_review_budget: "Review anggaran mingguan",
    mission_save_budget: "Simpan 10% sisa budget",
    badge_starter: "Starter",
    badge_starter_desc: "Capai Transaksi 50",
    badge_active: "Active User",
    badge_active_desc: "Capai Transaksi 100",
    badge_loyal: "Loyal User",
    badge_loyal_desc: "Capai Transaksi 150",
    badge_super: "Super User",
    badge_super_desc: "Capai Transaksi 200",
    badge_healthy: "Sehat Finansial",
    badge_healthy_desc: "Skor Finansial 80",
    badge_consistent: "Konsisten Sehat",
    badge_consistent_desc: "Tahan 80 > 1 Minggu",
    badge_paham: "Paham Finansial",
    badge_paham_desc: "Level Finansial 2",
    badge_bisa: "Bisa Finansial",
    badge_bisa_desc: "Level Finansial 3",
    badge_master: "Master Finansial",
    badge_master_desc: "Level Finansial 4",
    badge_pakar: "Pakar Finansial",
    badge_pakar_desc: "Level Finansial 5",
    level_0_title: "Pemula Finansial",
    level_1_title: "Pelajar Finansial",
    level_2_title: "Paham Finansial",
    level_3_title: "Bisa Finansial",
    level_4_title: "Master Finansial",
    level_5_title: "Pakar Finansial",
    // Profile & Settings Page
    settings: "Pengaturan",
    profile: "Profil & Pengaturan",
    profile_desc: "Kelola preferensi akun dan personalisasi aplikasi KasFlow Anda.",
    general: "Preferensi Umum",
    lang_name: "Bahasa Aplikasi",
    desc_lang: "Pilih bahasa yang Anda gunakan di aplikasi",
    app_mode: "Mode Aplikasi",
    mode_p: "Mengelola keuangan pribadi",
    mode_u: "Mengelola keuangan UMKM",
    theme_title: "Tema Tampilan",
    theme_d: "Mode Gelap",
    theme_l: "Mode Terang",
    notif: "Notifikasi Push",
    desc_notif: "Atur peringatan transaksi dan promo",
    achievements: "Pencapaian",
    achievements_desc: "Lihat Level Finansial & Koleksi Lencana",
    security: "Akun & Keamanan",
    privacy: "Ubah PIN & Sandi",
    desc_privacy: "Ubah PIN transaksi atau kata sandi Anda",
    change_acc: "Ganti / Tambah Akun",
    desc_change_acc: "Pindah ke akun KasFlow lain tanpa logout",
    help: "Bantuan",
    faq: "Aduan & FAQ",
    about: "Tentang KasFlow",
    back: "Kembali",
    transactions: "Transaksi",
    badges: "Lencana",
    streak: "Beruntun",
    logout: "Keluar Akun",
    select_lang: "Pilih Bahasa Aplikasi"
  },
  "English (US)": {
    mobile_summary_prefix: "Your",
    mobile_summary_suffix: "cash summary today.",
    nav_dashboard: "Dashboard",
    nav_transaksi: "Transactions",
    nav_insight: "Insights",
    nav_profil: "Profile",
    nav_beranda: "Home",
    btn_catat: "Add Transaction",
    mode_p_short: "Personal",
    mode_u_short: "SME",
    hello: "Hello",
    search_trans: "Search transaction history...",
    this_month: "this month",
    total_balance: "Total Active Balance",
    income: "Income",
    expense: "Expense",
    cashflow_trend: "Cash Flow Trend",
    category_dist: "Category Distribution",
    quick_action: "Quick Actions",
    add_income: "Add Income",
    add_expense: "Add Expense",
    scan_receipt: "Scan Receipt",
    scanning: "Scanning...",
    fin_health: "Financial Health",
    very_healthy: "Very Healthy",
    spending_controlled: "Spending is well-controlled",
    spending_optimized: "Spending has been optimized",
    critical: "Critical",
    warning: "Warning",
    safe: "Safe",
    danger: "Danger",
    risk_level: "Risk Level",
    recent_trans: "Recent Transactions",
    view_all: "View All",
    trans_type: "Type",
    cat_action: "Category & Activity",
    date_time: "Date & Time",
    status_label: "Status",
    done: "Success",
    pending: "Pending",
    add_title: "Add Transaction",
    add_desc: "Enter new cash transaction amount here.",
    amount: "Amount",
    trans_name: "Transaction Name",
    placeholder_name: "e.g. Electricity bill, Salary...",
    category: "Category",
    select_category: "Select Category",
    notes: "Notes",
    placeholder_notes: "Write transaction details...",
    save: "Save Transaction",
    saving: "Saving...",
    success_save: "Successfully recorded",
    error_name: "Transaction name is required!",
    error_amount: "Amount cannot be empty!",
    error_category: "Category is required!",
    error_save: "Failed to save transaction.",
    cat_sales: "Sales",
    cat_service: "Service Income",
    cat_capital: "Capital",
    cat_raw: "Raw Materials",
    cat_ops: "Operational",
    cat_marketing: "Marketing",
    cat_salary: "Salary",
    cat_bills: "Bills",
    cat_rent: "Rent",
    cat_others: "Others",
    trans_desc: "Monitor history on one screen.",
    trans_desc_mobile: "Track all your expenses and income.",
    trans_not_found: "Transactions not found",
    trans_not_found_desc: "No history matches your keyword.",
    export_title: "Export Report",
    export_pdf: "Download PDF",
    export_csv: "Download CSV",
    insight_subtitle: "Deep analysis of your cash flow.",
    smart_insight: "Smart Insight",
    insight_spending_prefix: "Your biggest spending this month is in",
    insight_tip_personal: "Try reducing outside snacks to save more.",
    insight_tip_umkm: "Make sure your selling price covers this capital.",
    based_on: "Based on spending",
    master_finansial: "Financial Master",
    to_level: "to Level 5",
    gamification_tip: "Great! Your spending is 15% more efficient (+50 XP).",
    more_saving: "More Savings",
    vs_last_month: "This month vs Last month",
    budget_category: "Budget Category",
    budget_desc: "Monitor your spending limits",
    budget_warning: "Warning: Over budget!",
    top_5_expense: "Top 5 Expenses",
    biggest_spending: "Biggest spending this month",
    insight_footer_title: "Watch Your Spending",
    insight_footer_desc: "Stay within budget to reach your goals.",
    add_budget_title: "Add New Budget",
    add_budget_desc: "Set budget limits for additional categories.",
    custom_category: "New Custom Category...",
    net_profit: "Net Profit",
    gross_income: "Gross Income",
    total_cost: "Total Cost",
    profit_margin: "Profit Margin",
    last_month: "Last Month",
    this_month_chart: "This Month",
    // Gamification (English)
    financial_level: "Financial Level",
    score_label: "Score",
    progress_to: "Progress to Level",
    collect_more_prefix: "Collect",
    collect_more_suffix: "more.",
    max_level_reached: "Congrats, you reached max level!",
    daily_missions: "Daily Missions",
    streak_days: "5 Day Streak!",
    mission_xp_desc: "Complete to get extra XP",
    level_up_notif: "Level Up!",
    congrats_reach: "Congrats! You reached rank",
    achievement_unlocked: "Achievement Unlocked!",
    new_badge_collect: "One more badge for you:",
    continue: "Continue",
    claim: "Claim!",
    top_user_percent: "You're in top 15% users!",
    badge_starter: "Starter",
    badge_starter_desc: "Reach 50 Transactions",
    badge_active: "Active User",
    badge_active_desc: "Reach 100 Transactions",
    badge_loyal: "Loyal User",
    badge_loyal_desc: "Reach 150 Transactions",
    badge_super: "Super User",
    badge_super_desc: "Reach 200 Transactions",
    badge_healthy: "Financial Healthy",
    badge_healthy_desc: "Financial Score 80",
    badge_consistent: "Consistently Healthy",
    badge_consistent_desc: "Hold 80 > 1 Week",
    badge_paham: "Financial Savvy",
    badge_paham_desc: "Financial Level 2",
    badge_bisa: "Financial Capable",
    badge_bisa_desc: "Financial Level 3",
    badge_master: "Financial Master",
    badge_master_desc: "Financial Level 4",
    badge_pakar: "Financial Expert",
    badge_pakar_desc: "Financial Level 5",
    level_0_title: "Financial Beginner",
    level_1_title: "Financial Learner",
    level_2_title: "Financial Savvy",
    level_3_title: "Financial Capable",
    level_4_title: "Financial Master",
    level_5_title: "Financial Expert",
    mission_daily_exp: "Record today's spending",
    mission_review_budget: "Review weekly budget",
    mission_save_budget: "Save 10% of remaining budget",
    settings: "Settings",
    profile: "Profile & Settings",
    profile_desc: "Manage account and personalize KasFlow.",
    general: "General Preferences",
    lang_name: "App Language",
    desc_lang: "Choose app language",
    app_mode: "App Mode",
    mode_p: "Personal finance management",
    mode_u: "SME finance management",
    theme_title: "Display Theme",
    theme_d: "Dark Mode",
    theme_l: "Light Mode",
    notif: "Push Notifications",
    desc_notif: "Set alerts",
    achievements: "Achievements",
    achievements_desc: "Financial Level & Badges",
    security: "Account & Security",
    privacy: "Change PIN & Password",
    desc_privacy: "Change your security details",
    change_acc: "Switch Account",
    desc_change_acc: "Switch accounts without logout",
    help: "Help",
    faq: "Help & FAQ",
    about: "About KasFlow",
    back: "Back",
    transactions: "Transactions",
    badges: "Badges",
    streak: "Streak",
    logout: "Logout",
    select_lang: "Select App Language"
  },
  "Japanese": {
    mobile_summary_prefix: "本日の",
    mobile_summary_suffix: "キャッシュ要約です。",
    nav_dashboard: "ダッシュボード",
    nav_transaksi: "取引履歴",
    nav_insight: "分析インサイト",
    nav_profil: "プロフィール",
    nav_beranda: "ホーム",
    btn_catat: "取引を記録",
    mode_p_short: "個人",
    mode_u_short: "中小企業",
    hello: "こんにちは",
    search_trans: "取引履歴を検索...",
    this_month: "今月",
    total_balance: "現在の総残高",
    income: "収入",
    expense: "支出",
    cashflow_trend: "キャッシュフロー推移",
    category_dist: "カテゴリー別の割合",
    quick_action: "クイック操作",
    add_income: "収入を記帳",
    add_expense: "支出を記帳",
    scan_receipt: "レシートをスキャン",
    scanning: "スキャン中...",
    fin_health: "財務状況チェック",
    very_healthy: "非常に健全",
    spending_controlled: "支出が管理されています",
    spending_optimized: "支出が最適化されています",
    critical: "危険",
    warning: "注意",
    safe: "安全",
    danger: "危険",
    risk_level: "リスクレベル",
    recent_trans: "最近の取引履歴",
    view_all: "すべて見る",
    trans_type: "種別",
    cat_action: "カテゴリーと内容",
    date_time: "取引日時",
    status_label: "ステータス",
    done: "完了",
    pending: "保留中",
    add_title: "取引を追加",
    add_desc: "金額を入力してください。",
    amount: "金額",
    trans_name: "取引名",
    placeholder_name: "例：電気代...",
    category: "カテゴリー",
    select_category: "カテゴリーを選択",
    notes: "メモ",
    placeholder_notes: "詳細を記入...",
    save: "取引を保存",
    saving: "保存中...",
    success_save: "記録に成功",
    error_name: "名前が必要です！",
    error_amount: "金額が必要です！",
    error_category: "カテゴリーが必要です！",
    error_save: "保存に失敗しました。",
    cat_sales: "売上",
    cat_service: "サービス収益",
    cat_capital: "資本金",
    cat_raw: "原材料費",
    cat_ops: "運営費",
    cat_marketing: "マーケティング",
    cat_salary: "基本給",
    cat_bills: "請求書",
    cat_rent: "賃料",
    cat_others: "その他",
    trans_desc: "完全な履歴を監視します。",
    trans_desc_mobile: "支出と収入を追跡します。",
    trans_not_found: "取引が見つかりません",
    trans_not_found_desc: "履歴はありません。",
    export_title: "レポートのエクスポート",
    export_pdf: "PDFをダウンロード",
    export_csv: "CSVをダウンロード",
    analytics: "財務分析",
    monthly_report: "月次レポート",
    net_profit: "純利益",
    gross_income: "総収入",
    total_cost: "総費用",
    profit_margin: "利益率",
    last_month: "先月",
    this_month_chart: "今月",
    // Gamification (Japanese)
    financial_level: "財務レベル",
    score_label: "スコア",
    progress_to: "次レベルまで",
    collect_more_prefix: "あと",
    collect_more_suffix: "XP必要です。",
    max_level_reached: "最大レベルに到達しました！",
    daily_missions: "デイリーミッション",
    streak_days: "5日連続！",
    mission_xp_desc: "クリアしてXPをゲット",
    level_up_notif: "レベルアップ！",
    congrats_reach: "おめでとう！ランクに到達:",
    achievement_unlocked: "実績解除！",
    new_badge_collect: "新しいバッジ:",
    continue: "次へ",
    claim: "受け取る！",
    top_user_percent: "上位15%のユーザー",
    badge_starter: "スターター",
    badge_starter_desc: "取引50回達成",
    badge_active: "アクティブユーザー",
    badge_active_desc: "取引100回達成",
    badge_loyal: "ロイヤルユーザー",
    badge_loyal_desc: "取引150回達成",
    badge_super: "スーパーユーザー",
    badge_super_desc: "取引200回達成",
    badge_healthy: "財務健全",
    badge_healthy_desc: "財務スコア80",
    badge_consistent: "継続的健全",
    badge_consistent_desc: "1週間スコア80維持",
    badge_paham: "財務サビー",
    badge_paham_desc: "財務レベル2",
    badge_bisa: "財務能力者",
    badge_bisa_desc: "財務レベル3",
    badge_master: "財務マスター",
    badge_master_desc: "財務レベル4",
    badge_pakar: "財務エキスパート",
    badge_pakar_desc: "財務レベル5",
    level_0_title: "財務初心者",
    level_1_title: "財務学習者",
    level_2_title: "財務サビー",
    level_3_title: "財務能力者",
    level_4_title: "財務マスター",
    level_5_title: "財務エキスパート",
    mission_daily_exp: "今日の支出を記録する",
    mission_review_budget: "週間予算を確認する",
    mission_save_budget: "予算の10%を貯金する",
    settings: "設定",
    profile: "プロフィールと設定",
    profile_desc: "設定を管理。",
    general: "全般設定",
    lang_name: "アプリの言語",
    desc_lang: "言語を選択",
    app_mode: "アプリモード",
    mode_p: "個人財務管理",
    mode_u: "中小企業財務管理",
    theme_title: "表示テーマ",
    theme_d: "ダークモード",
    theme_l: "ライトモード",
    notif: "プッシュ通知",
    desc_notif: "アラートを設定",
    achievements: "実績",
    achievements_desc: "レベルとバッジ",
    security: "セキュリティ",
    privacy: "PINの変更",
    desc_privacy: "パスワードを変更",
    change_acc: "アカウント切り替え",
    desc_change_acc: "ログアウトせずに切り替え",
    help: "ヘルプ",
    faq: "ヘルプとFAQ",
    about: "KasFlowについて",
    back: "戻る",
    logout: "ログアウト",
    select_lang: "アプリの言語を選択"
  }
};

  const t = (key) => translations[language]?.[key] || key;

  useEffect(() => {
    const root = window.document.documentElement;
    theme === 'dark' ? root.classList.add('dark') : root.classList.remove('dark');
    localStorage.setItem('theme', theme);
  }, [theme]);

  useEffect(() => localStorage.setItem('kasflow-mode', mode), [mode]);
  useEffect(() => localStorage.setItem('notifications', JSON.stringify(notifications)), [notifications]);
  useEffect(() => localStorage.setItem('kasflow-lang', language), [language]);

  const toggleMode = () => setMode((prev) => (prev === 'umkm' ? 'personal' : 'umkm'));
  
  const toggleTheme = () => {
    const nextTheme = theme === 'light' ? 'dark' : 'light';
    if (!document.startViewTransition) { setTheme(nextTheme); return; }
    document.startViewTransition(() => { flushSync(() => setTheme(nextTheme)); });
  };

  const toggleNotifications = () => setNotifications((prev) => !prev);

  return (
    <ModeContext.Provider 
      value={{ 
        mode, 
        theme, 
        notifications, 
        language,
        setLanguage,
        t,
        toggleMode, 
        toggleTheme, 
        toggleNotifications 
      }}
    >
      {children}
    </ModeContext.Provider>
  );
}

export const useMode = () => {
  const context = useContext(ModeContext);
  if (!context) throw new Error("useMode must be used within a ModeProvider!");
  return context;
};